source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem "dry-rails", path: "../../.."

gem "rails", "~> 8.1.0"
gem "jbuilder"
gem "bootsnap", require: false

gem "tzinfo-data", platforms: %i[windows jruby]
